/**
 * --- Funnel Utility Functions ---
 * This file contains helper functions related to creating and managing funnel structures.
 * Keeping these functions separate helps to maintain a clean and organized codebase.
 */

import { FunnelFlow, FunnelStage, FunnelBlock, FunnelBlockOption, SEND_DM_STAGE_NAME } from "@/lib/types/funnel";

interface Resource {
	id: string;
	type: string;
	name: string;
	link: string;
	code: string;
	category: string;
}

interface Funnel {
	id: string;
	name: string;
	allocation: number;
	resources: Resource[];
	flow: FunnelFlow | null;
	isDeployed: boolean;
	delay: number;
}

/**
 * Creates a basic funnel object with default values. This is used when a new funnel
 * is created by the user, providing a clean slate to start from.
 * @param {string} id - The unique identifier for the funnel (e.g., 'A', 'B').
 * @param {string} name - The display name for the funnel.
 * @param {number} [allocation=0] - The percentage of traffic allocated to this funnel.
 * @param {boolean} [isDeployed=false] - Whether the funnel is currently live.
 * @returns {Funnel} A new funnel object.
 */
export const createDefaultFunnel = (
	id: string,
	name: string,
	allocation = 0,
	isDeployed = false,
): Funnel => ({
	id,
	name,
	allocation,
	resources: [], // A new funnel starts with no resources.
	flow: null, // The visual flow is null until generated by the AI.
	isDeployed,
	delay: 0, // The welcome message delay defaults to 0 seconds.
});

/**
 * Creates a minimal flow structure for "Create Merchant Manually" (no AI generation).
 * First stage is SEND_DM (message icon); then WELCOME or OFFER. startBlockId points to Send DM block.
 * @param funnelId - The funnel ID (used for block/stage IDs).
 * @param merchantType - "qualification" | "upsell". Upsell gets OFFER stage with one product block.
 * @returns Minimal FunnelFlow.
 */
export const createMinimalFlow = (
	funnelId: string,
	merchantType: "qualification" | "upsell"
): FunnelFlow => {
	const sendDmBlockId = `send-dm-block-${funnelId}`;
	const sendDmStageId = `send-dm-stage-${funnelId}`;
	if (merchantType === "upsell") {
		const offerBlockId = `offer-block-${funnelId}`;
		const offerStageId = `offer-stage-${funnelId}`;
		return {
			stages: [
				{
					id: sendDmStageId,
					name: SEND_DM_STAGE_NAME,
					blockIds: [sendDmBlockId],
					explanation: "Send DM to user (Whop native chat); not shown in-app",
				},
				{
					id: offerStageId,
					name: "OFFER",
					blockIds: [offerBlockId],
					explanation: "First product offer",
					cardType: "product",
				},
			],
			blocks: {
				[sendDmBlockId]: {
					id: sendDmBlockId,
					message: "Write DM there...",
					options: [{ text: "Continue", nextBlockId: offerBlockId }],
					sendDmBlock: true,
				},
				[offerBlockId]: {
					id: offerBlockId,
					message: "",
					options: [
						{ text: "Upsell", nextBlockId: null },
						{ text: "Downsell", nextBlockId: null },
					],
				},
			},
			startBlockId: sendDmBlockId,
		};
	}
	const welcomeBlockId = `welcome-block-${funnelId}`;
	const welcomeStageId = `welcome-stage-${funnelId}`;
	return {
		stages: [
			{
				id: sendDmStageId,
				name: SEND_DM_STAGE_NAME,
				blockIds: [sendDmBlockId],
				explanation: "Send DM to user (Whop native chat); not shown in-app",
			},
			{
				id: welcomeStageId,
				name: "WELCOME",
				blockIds: [welcomeBlockId],
				explanation: "Welcome message sent to users",
			},
		],
		blocks: {
			[sendDmBlockId]: {
				id: sendDmBlockId,
				message: "Write DM there...",
				options: [{ text: "Continue", nextBlockId: welcomeBlockId }],
				sendDmBlock: true,
			},
			[welcomeBlockId]: {
				id: welcomeBlockId,
				message: "",
				options: [],
			},
		},
		startBlockId: sendDmBlockId,
	};
};

/**
 * Ensures a funnel flow has a SEND_DM stage. If one already exists, returns the flow as-is.
 * If missing, prepends a SEND_DM stage and block, pointing its option to the current startBlockId.
 * The new startBlockId becomes the SEND_DM block so the flow structure stays consistent.
 * @param flow - The existing funnel flow.
 * @param funnelId - The funnel ID (used to generate deterministic block/stage IDs).
 * @returns The flow with a SEND_DM stage guaranteed.
 */
export const ensureSendDmStage = (flow: FunnelFlow, funnelId: string): FunnelFlow => {
	const hasSendDm = flow.stages.some((s) => s.name === SEND_DM_STAGE_NAME);
	if (hasSendDm) return flow;

	const sendDmBlockId = `send-dm-block-${funnelId}`;
	const sendDmStageId = `send-dm-stage-${funnelId}`;

	return {
		...flow,
		startBlockId: sendDmBlockId,
		stages: [
			{
				id: sendDmStageId,
				name: SEND_DM_STAGE_NAME,
				blockIds: [sendDmBlockId],
				explanation: "Send DM to user (Whop native chat); not shown in-app",
			},
			...flow.stages,
		],
		blocks: {
			...flow.blocks,
			[sendDmBlockId]: {
				id: sendDmBlockId,
				message: "Write DM there...",
				options: [{ text: "Continue", nextBlockId: flow.startBlockId }],
				sendDmBlock: true,
			},
		},
	};
};

/**
 * Creates a funnel flow object specifically for displaying errors.
 * This is used when the AI generation fails, providing a clear error message
 * to the user within the funnel visualizer.
 * @returns {FunnelFlow} An error-specific funnel flow object.
 */
export const createErrorFunnelFlow = (): FunnelFlow => ({
	startBlockId: "error_start",
	stages: [
		{
			id: "stage-error",
			name: "ERROR",
			explanation: "Generation failed.",
			blockIds: ["error_start"],
		},
	],
	blocks: {
		error_start: {
			id: "error_start",
			message:
				"An error occurred during generation. Please see the message above and try again.",
			options: [],
		},
	},
});

/**
 * Returns the stage name for the block (for display only). Do not use for control flow.
 */
export function getStageNameForBlock(blockId: string, funnelFlow: FunnelFlow): string {
	const stage = funnelFlow.stages.find((s) => s.blockIds.includes(blockId));
	return stage?.name ?? "UNKNOWN";
}

/**
 * Progress 0–100% based on which stage contains the current block.
 * Formula: (stage position / total stages) × 100 — e.g. stage 1/5 = 20%, 2/5 = 40%, 5/5 = 100%.
 * Works for any number of stages (qualification and upsell). No hardcoded percentages.
 * @param blockId - Current block ID (from conversation); null when no block (e.g. completed).
 * @param stages - funnelFlow.stages (order defines position)
 */
export function getFunnelProgressPercentageFromBlock(
	blockId: string | null,
	stages: Array<{ blockIds: string[] }>,
): number {
	if (!stages?.length || !blockId) return 0;
	const stageIndex = stages.findIndex((s) => s.blockIds?.includes(blockId));
	if (stageIndex < 0) return 0;
	const total = stages.length;
	const position = stageIndex + 1;
	return position >= total ? 100 : (position / total) * 100;
}

/**
 * Progress 0–100% based on current stage name (fallback when blockId not available).
 * Formula: (stage position / total stages) × 100. Stage name match is case-insensitive.
 * Prefer getFunnelProgressPercentageFromBlock when you have currentBlockId (correct for upsell with duplicate stage names).
 */
export function getFunnelProgressPercentage(
	currentStageName: string,
	stages: Array<{ name: string; blockIds: string[] }>,
): number {
	if (!stages?.length || !currentStageName) return 0;
	const normalized = currentStageName.trim().toUpperCase();
	const stageIndex = stages.findIndex(
		(s) => (s.name ?? "").trim().toUpperCase() === normalized,
	);
	if (stageIndex < 0) return 0;
	const total = stages.length;
	const position = stageIndex + 1;
	return position >= total ? 100 : (position / total) * 100;
}

/**
 * True if the block belongs to a stage with cardType === "product".
 * Use this (not stage.name) to decide: show product CTA button, hide numbered options in message.
 */
export function isProductCardBlock(blockId: string, funnelFlow: FunnelFlow): boolean {
	const stage = funnelFlow.stages.find((s) => s.blockIds.includes(blockId));
	return stage?.cardType === "product";
}

/**
 * Button label for product cards: "Claim!" for value-delivery stages, "Get Started!" otherwise.
 * Uses stage.name for value-delivery detection (display-only; can be replaced by stage.variant later).
 */
export function getProductCardButtonLabel(blockId: string, funnelFlow: FunnelFlow): "Claim!" | "Get Started!" {
	const stage = funnelFlow.stages.find((s) => s.blockIds.includes(blockId));
	return stage?.name === "VALUE_DELIVERY" ? "Claim!" : "Get Started!";
}

/**
 * Returns options array for an upsell block from upsellBlockId/downsellBlockId (for layout/lines).
 * Use when reading or persisting upsell blocks so existing layout code works.
 * @param validBlockIds - When provided, nextBlockId is set to null if the target is not in this set (avoids "missing block" validation errors).
 */
export function getUpsellBlockOptions(block: FunnelBlock, validBlockIds?: Set<string>): FunnelBlockOption[] {
	let upsellId = block.upsellBlockId ?? null;
	let downsellId = block.downsellBlockId ?? null;
	if (validBlockIds) {
		if (upsellId != null && !validBlockIds.has(upsellId)) upsellId = null;
		if (downsellId != null && !validBlockIds.has(downsellId)) downsellId = null;
	}
	return [
		{ text: "Upsell", nextBlockId: upsellId },
		{ text: "Downsell", nextBlockId: downsellId }
	];
}

/**
 * Gets the last bot message from a stage by finding the last block in that stage with a message
 * @param stageId - The ID of the stage to get the message from
 * @param funnelFlow - The funnel flow containing stages and blocks
 * @returns The last bot message text from the stage, or null if not found
 */
export function getLastBotMessageFromStage(
	stageId: string,
	funnelFlow: FunnelFlow
): string | null {
	const stage = funnelFlow.stages.find((s) => s.id === stageId);
	if (!stage) return null;

	// Get all blocks in this stage
	const stageBlocks = stage.blockIds
		.map((id) => funnelFlow.blocks[id])
		.filter(Boolean);

	// Find the last block that has a message
	for (let i = stageBlocks.length - 1; i >= 0; i--) {
		const block = stageBlocks[i];
		if (block?.message) {
			return block.message;
		}
	}

	return null;
}
