#!/bin/bash

# Script to set up local Supabase environment
echo "🚀 Setting up local Supabase environment..."

# Create local environment file
cat > .env.local << 'EOF'
# Local Supabase Development Environment
# Generated by Supabase CLI

# Supabase Local URLs
NEXT_PUBLIC_SUPABASE_URL=http://127.0.0.1:54321
SUPABASE_URL=http://127.0.0.1:54321

# Supabase Local Keys
NEXT_PUBLIC_SUPABASE_ANON_KEY=sb_publishable_ACJWlzQHlZjBrEguHvfOxg_3BJgxAaH
SUPABASE_ANON_KEY=sb_publishable_ACJWlzQHlZjBrEguHvfOxg_3BJgxAaH
SUPABASE_SERVICE_ROLE_KEY=sb_secret_N7UND0UgjKTVK-Uodkm0Hg_xSvEMPvz

# Local Database Connection
POSTGRES_URL=postgresql://postgres:postgres@127.0.0.1:54322/postgres
POSTGRES_URL_NON_POOLING=postgresql://postgres:postgres@127.0.0.1:54322/postgres

# Local S3 Storage (for file uploads)
S3_ACCESS_KEY=625729a08b95bf1b7ff351a663f3a23c
S3_SECRET_KEY=850181e4652dd023b7a98c58ae0d2d34bd487ee0cc3254aed6eda37307425907
S3_REGION=local
S3_ENDPOINT=http://127.0.0.1:54321/storage/v1/s3

# Keep your existing API keys
GEMINI_API_KEY="AIzaSyDX-TeF0XmYbszNgHzrUmPDrUzRjNrKG5I"
WHOP_API_KEY="Pqm2m96bR6B6fyX11TJI4J2Pbjpg-dj3sp60X4NPH5Q"
WHOP_WEBHOOK_SECRET="ws_4217d473cd962c529dbccd16f0a3230ef27d58cf1a25e42723dd2128a5aaa056"
NEXT_PUBLIC_WHOP_AGENT_USER_ID="user_23pKfUV4sWNlH"
NEXT_PUBLIC_WHOP_APP_ID="app_FInBMCJGyVdD9T"
NEXT_PUBLIC_WHOP_COMPANY_ID="biz_QG3JlRNIE910HW"
EOF

echo "✅ Local environment file created!"
echo "📝 You can now use local Supabase instead of the cloud version"
echo ""
echo "🔗 Local Supabase URLs:"
echo "   - Studio: http://127.0.0.1:54323"
echo "   - API: http://127.0.0.1:54321"
echo "   - Database: postgresql://postgres:postgres@127.0.0.1:54322/postgres"
echo ""
echo "🚀 To start your app with local Supabase:"
echo "   pnpm dev"
echo ""
echo "📊 To open Drizzle Studio:"
echo "   pnpm run db:studio"
